### ISSUE TITLE
make template repo migration tool

### ISSUE THREAD

**Issue by jrbl** [edx/edx-certificates#25]
Today I migrated our old cert configuration to the new format in I python in about 5 minutes. It just occurred to me that it would help edx.org run the new repo if I automated that. It's a small job but I'm on the train without a seat so this is a reminder.

**Comment by stvstnfrd** [comment]
edx hasn't/won't use the new format, as PDF certs have (sadly) been long deprecated in favor of Web Certs.

Hope you're well @jrbl !
